### ISSUE TITLE
No longer automatically scrolling to bottom of console with new logged input

### ISSUE THREAD

**Issue by deathcap** [deathcap/console-widget#6]
console-widget should scroll to the bottom of the console when new lines are logged, but it no longer appears to (used to?)

Testing on Chrome 40

Maybe related to GH-2 Firefox scrollByLines?

**Comment by z3t0** [comment]
I noticed this aswell and thought it was a part of the implementation, guess not...

**Comment by z3t0** [comment]
Chrome 41

**Comment by deathcap** [comment]
Noticed this again (when updating https://github.com/voxel/voxel-clientmc, automatic scrolling is very useful for chat), isolated on http://deathcap.github.io/console-widget/ demo. Scrolling works on Safari 9.0.3 but not Chrome 48.0.2564.97.

**Comment by deathcap** [comment]
http://stackoverflow.com/questions/18073461/why-scrollbylines-and-scrollbypages-not-working says to "use the cross-browser scrollBy method instead" of scrollByLines

**Comment by deathcap** [comment]
Changed to use scrollBy in `scrollOutput()`, but will also need to remove scrollByLines usage for https://github.com/deathcap/console-widget/issues/2
